name: sponsor 💜
on: 
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  sponsor:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.sender.login, '[bot]') && !endsWith(github.event.sender.login, 'bot') }}
    steps:
      - name: 💜 sponsor
        uses: devlooped/actions-sponsor@v1
        with:
          # The account to check for sponsorship. 
          # Defaults to the repository owner `${{ github.repository.owner }}`
          sponsorable: aritchie

          # The token to use for querying the GitHub API for sponsorship information. 
          # Typically set to ${{ secrets.GH_TOKEN }}.
          token: ${{ secrets.GH_TOKEN }}
